name: Validação de HTML

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  html-validation:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Validação do HTML
        uses: Cyb3r-Jak3/html-validate-action@v1
        with:
          config: .htmlvalidate.json
        continue-on-error: false

      - uses: actions/checkout@v4

      - name: Run Discord Webhook
        uses: johnnyhuy/actions-discord-git-webhook@main
        with:
          webhook_url: ${{ secrets.DISCORD_WEBHOOK }}