name: Validação de HTML

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  html-validation:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Validação do HTML
        uses: wearerequired/html-validate-action@v1
        with:
          config: .htmlvalidate.json
        continue-on-error: false